### ISSUE TITLE
How to execute quartz-manager

### ISSUE THREAD

**Issue by anujgandharv** [fabioformosa/quartz-manager#1]
Hi Fabio,
 I chanced upon your quartz-manager repository and it resembles to something I have been looking for. 
So I downloaded and ran mvn spring-boot:run and the application started successfully.

But I do not know where to go from there. What are the exact steps. Can you provide a small guide for me of the various endpoints you have and how to navigate through them. 

http://localhost:8080/manager 

doesnt work.

Thanks,
Anuj Kumar

**Comment by fabioformosa** [comment]
Hi Anuj,
in the next hours I'll write a short guide to run. Meanwhile, try this url:

http://localhost:9000/quartz-manager/manager
(credential to log: admin/admin)

Let me know.

**Comment by anujgandharv** [comment]
Yes I figured it out already. I can login as well as look start/pause the scheduer. I will keep exploring it and will ping in case I have issues

**Comment by fabioformosa** [comment]
As I promised, I've just added a README file at the root of project. You could contribute if you would improve it.
I close this issue.

**Comment by anujgandharv** [comment]
Thanks Fabio.
