### ISSUE TITLE
Set up specify time for each job

### ISSUE THREAD

**Issue by ngochai27595** [fabioformosa/quartz-manager#16]
Did we have the feature to set specify time (minute, hour, day, week,..) for each job?

**Comment by fabioformosa** [comment]
That's a feature in the [roadmap](https://github.com/fabioformosa/quartz-manager/projects/4). Right now you can set how many times a day the job to be run.

**Comment by fabioformosa** [comment]
Hi @ngochai27595 ,
a new release (v4.0.4)  has been released. Now it's possible to set a specific start date time for the scheduled job.
