### ISSUE TITLE
cannot build with maven

### ISSUE THREAD

**Issue by daniboy82** [fabioformosa/quartz-manager#24]
daniel@maggie:~/quartz-manager/quartz-manager-parent/quartz-manager-web$ mvn spring-boot:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ---------< it.fabioformosa.quartz-manager:quartz-manager-web >----------
[INFO] Building Quartz Manager Web 2.2.2-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:2.3.4.RELEASE:run (default-cli) > test-compile @ quartz-manager-web >>>
[WARNING] The POM for it.fabioformosa.quartz-manager:quartz-manager-api:jar:2.2.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.sun.xml.bind:jaxb-osgi:jar:2.2.10 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.126 s
[INFO] Finished at: 2020-10-16T16:29:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project quartz-manager-web: Could not resolve dependencies for project it.fabioformosa.quartz-manager:quartz-manager-web:war:2.2.2-SNAPSHOT: Could not find artifact it.fabioformosa.quartz-manager:quartz-manager-api:jar:2.2.2-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
daniel@maggie:~/quartz-manager/quartz-manager-parent/quartz-manager-web$

**Comment by fabioformosa** [comment]
Thank you. Let me check.

**Comment by fabioformosa** [comment]
you have to type ```mvn install``` inside the project ```quartz-manager-parent```

**Comment by daniboy82** [comment]
It worked. I was doing wrong, thank you!
